### ISSUE TITLE
DeserializationError during initial migration

### ISSUE THREAD

**Issue by naegelyd** [chop-dbhi/varify#268]
When running `syncdb --migrate` the following error is seen:

```
> varify:0002_avocado_metadata_migration
> varify:0003_fix_sequence_problems
- Loading initial data for varify.
Problem installing fixture 'varify/fixtures/initial_data.json': Traceback (most recent call last):
  File "/Users/ohara/varify-env/lib/python2.7/site-packages/django/core/management/commands/http://loaddata.py", line 190, in handle
    for obj in objects:
  File "/Users/ohara/varify-env/lib/python2.7/site-packages/django/core/serializers/http://json.py", line 47, in Deserializer
    raise DeserializationError(e)
DeserializationError: ContentType matching query does not exist.
```

**Comment by naegelyd** [comment]
The fix was buggy and has been reverted. See PR comments for more info.
